### ISSUE TITLE
TTS 

### ISSUE THREAD

**Issue by AdrianoFF10** [Goncalo287/savi_t2#6]
Implementei o TTS no main, contudo acho que ficaria bem adicionar mais alguns tópicos, tal como o objeto mais longe do centro da mesa ou algo deste género. Digam o que acham desta sugestão e se vale a pena implementar outras.

**Comment by Goncalo287** [comment]
Adicionei uma parte relativa à posição dos objetos (qual está mais perto do centro da mesa) e simplifiquei o texto para os casos em que existe apenas um objeto (cenas criadas a partir da câmara)
